---
      - name: "Check if supervisor is already added in services CentOS6"
        script: ../files/check_if_service_is_on.sh supervisord
        register: supervisor_service

      - name: "Add supervisord as a service CentOS6"
        command: chkconfig --add supervisord
        when: (supervisor_service.stdout == "0")

      - name: "Check if redis service is on CentOS6"
        script: ../files/check_if_service_is_on.sh redis
        register: redis_is_on
   
      - name: "Set redis service on CentOS6"
        shell: chkconfig redis on
        when: (redis_is_on.stdout == "0")

      - name: "Check if mysql service is on CentOS6"
        script: ../files/check_if_service_is_on.sh mysql
        register: mysql_is_on

      - name: "Set mysql service on CentOS6"
        shell: chkconfig mysql on
        when: (mysql_is_on.stdout == "0")

      - name: "Check if nginx service is on CentOS6"
        script: ../files/check_if_service_is_on.sh nginx
        register: nginx_is_on
 
      - name: "Set nginx service on CentOS6"
        shell: chkconfig nginx on
        when: (nginx_is_on.stdout == "0")

      - name: "Check if supervisord service is on CentOS6"
        script: ../files/check_if_service_is_on.sh supervisord
        register: supervisord_is_on

      - name: "Set supervisord service on CentOS6"
        shell: chkconfig supervisord on
        when: (supervisord_is_on.stdout == "0")
