---

     - name: "Generate frappe password"
       shell: echo `cat /dev/urandom | tr -dc "a-zA-Z0-9" | head -c 16`
       register: frappe_pass

     - name: "Generate password for MariaDB"
       shell: echo `cat /dev/urandom | tr -dc "a-zA-Z0-9" | head -c 16`
       register: msq_pass

     - name: "Generate administrator password"
       shell: echo `cat /dev/urandom | tr -dc "a-zA-Z0-9" | head -c 16`
       register: admin_pass

     - name: "Save frappe password"
       shell: echo "frappe password:" > ~/frappe_passwords.sh {{frappe_pass.stdout}} >> ~/frappe_passwords.txt

     - name: "Save MariaDB root password"
       shell: echo "MariaDB root password:" >> ~/frappe_passwords.sh {{msq_pass.stdout}} >> ~/frappe_passwords.txt

     - name: "Save administrator password"
       shell: echo "administrator password:" >> ~/frappe_passwords.sh {{admin_pass.stdout}} >> ~/frappe_passwords.txt
