---

     - name: "Install packages for Debian 8"
       apt: pkg={{ item }} state=present
       with_items:
            - libtiff5-dev
            - libjpeg62-turbo-dev
            - zlib1g-dev
            - libfreetype6-dev
            - liblcms2-dev
            - libwebp-dev
            - tcl8.5-dev
            - tk8.5-dev
            - python-tk
