---

     - name: "Install packages for Ubuntu/Debian except from Precise and 8"
       apt: pkg={{ item }} state=present
       with_items:
            - libtiff5-dev
            - libjpeg8-dev
            - zlib1g-dev
            - libfreetype6-dev
            - liblcms2-dev
            - libwebp-dev
            - tcl8.6-dev
            - tk8.6-dev
            - python-tk
