---
# tasks file for install_packages
  
     - name: "Check if there is already frappe_passwords.sh file"
       stat: path=/root/frappe_passwords.sh
       register: passwords_exist

     - include: generate_passwords.yml
       when: passwords_exist.stat.exists == False

     - include: setup_debconf.yml
       when: (ansible_distribution == "Debian")

###### Install bunch of packages
     - include: install_packages_deb.yml
       when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

     - include: install_packages_precise.yml
       when: (ansible_distribution_release == "precise")

     - include: install_packages_deb8.yml
       when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")

     - include: install_packages_deb_else.yml
       when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu") and (ansible_distribution_major_version != "8" and ansible_distribution_release == "precise")

     - name: "Install wget CentOS"
       when: (ansible_distribution == "CentOS")
       yum: name=wget state=present

     - name: "Install Development tools CentOS"
       when: (ansible_distribution == "CentOS")
       yum: name="@Development tools" state=present

     - include: install_packages_centos6.yml
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

     - include: install_packages_centos7.yml
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

     - include: install_supervisor_centos6.yml
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

###### Configure & launch services
     - include: configure_services_centos6.yml
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

     - include: start_services_centos6.yml
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

     - include: configure_services_centos7.yml
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

     - include: start_services_centos7.yml
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

     - name: "Check if need to configure MariaDB Debian"
       stat: path=/etc/mysql/conf.d/barracuda.cnf 
       register: mariadb_configuration_deb
       when: (ansible_distribution == "Debian")

     - name: "Create MariaDB configuration Debian"
       script: ../files/create_mariadb_config.sh /etc/mysql/conf.d/barracuda.cnf
       when: (ansible_distribution == "Debian") and (mariadb_configuration_deb.stat.exists == False)

     - name: "Check if need to configure MariaDB CentOS"
       stat: path=/etc/my.cnf.d/barracuda.cnf
       register: mariadb_configuration_cent
       when: (ansible_distribution == "CentOS")

     - name: "Create MariaDB configuration CentOS"
       script: ../files/create_mariadb_config.sh /etc/my.cnf.d/barracuda.cnf
       when: (ansible_distribution == "CentOS") and (mariadb_configuration_cent.stat.exists == False)

     - name: "Restart MariaDB service CentOS7"
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") 
       service: name=mariadb state=restarted
    
     - name: "Restart MariaDB service CentOS6"
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
       service: name=mysql state=restarted

     - name: "Restart MariaDB service Debian/Ubuntu"
       when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
       service: name=mysql state=restarted

