---
     - name: "Check if postfix hostname is already configured"
       shell: debconf-show postfix | grep mailname | wc -l
       register: postfix_mailname

     - name: "Debconf postfix hostname"
       script: ../files/debconf_postfix_mailname.sh
       when: (postfix_mailname.stdout == "0")

     - name: "Check if postfix main_mailer_type is already configured"
       shell: debconf-show postfix | grep main_mailer_type | wc -l
       register: postfix_main_mailer_type

     - name: "Debconf postfix main_mailer_type"
       script: ../files/debconf_postfix_main_mailer.sh
       when: (postfix_main_mailer_type.stdout == "0")

     - name: "Check if MariaDB password is already configured"
       shell: debconf-show mariadb-server-5.5 | grep "password" | wc -l
       register: pass_configured

     - name: "Debconf MariaDB password"
       script: ../files/set_mariadb_password.sh {{ msq_pass }}  
       when: (pass_configured.stdout == "0")

