---

- name: install pillow prerequisites for Ubuntu < 14.04
  apt: pkg={{ item }} state=present force=yes
  with_items:
   - libjpeg8-dev
   - libtiff4-dev
   - tcl8.5-dev
   - tk8.5-dev
  when: ansible_distribution_version | version_compare('14.04', 'lt')

- name: install pillow prerequisites for Ubuntu >= 14.04
  apt: pkg={{ item }} state=present force=yes
  with_items:
   - libjpeg8-dev
   - libtiff5-dev
   - tcl8.6-dev
   - tk8.6-dev
  when: ansible_distribution_version | version_compare('14.04', 'ge')

...