---

- name: install pillow prerequisites for Ubuntu < 14.04
  apt: pkg={{ item }} state=present force=yes
  with_items:
   - libjpeg8-dev
   - libtiff4-dev
   - tcl8.5-dev
   - tk8.5-dev
  when: ansible_distribution_version | version('14.04', 'lt')

- name: install pillow prerequisites for Ubuntu >= 14.04
  apt: pkg={{ item }} state=present force=yes
  with_items:
   - libjpeg8-dev
   - libtiff5-dev
   - tcl8.6-dev
   - tk8.6-dev
  when: ansible_distribution_version | version('14.04', 'ge')


- name: install pdf prerequisites for Ubuntu < 18.04
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - libssl-dev
  when: ansible_distribution_version | version('18.04', 'lt')

- name: install pdf prerequisites for Ubuntu >= 18.04
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - libssl1.0-dev
  when: ansible_distribution_version | version('18.04', 'ge')

...
