---
  - name: Install supervisor
    pip:
      name: supervisor
      state: present
    become: yes
    become_user: root

    - name: Add supervisord into init.d
      template:
        src: templates/supervisor_init_d.cnf
        dest: /etc/init.d/supervisord
      become: yes
      become_user: root

    - name: Changes permissions supervisord in init.d
      file:
        state: file
        path: /etc/init.d/supervisord
        mode: "+x"
      become: yes
      become_user: root

    - name: Add supervisord to sysconfig
      template:
        src: templates/supervisord_sysconfig.cnf
        dest: /etc/sysconfig/supervisord
      become: yes
      become_user: root

    - name: Add supervisord to /etc
      template:
        src: templates/supervisord.cnf
        dest: /etc/supervisord.conf
      become: yes
      become_user: root

    - name: Start supervisor service
      service:
        name: supervisord
        state: started
        enabled: yes
      become: yes
      become_user: root
