---
  - name: Add apt key for mariadb for Ubuntu < 16.04
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db state=present
    become: yes
    become_user: root
    when: ansible_distribution_version | version_compare('16.04', 'lt')

  - name: Add apt key for mariadb for Ubuntu >= 16.04
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xF1656F24C74CD1D8 state=present
    become: yes
    become_user: root
    when: ansible_distribution_version | version_compare('16.04', 'ge')

  - name: Add apt repository
    apt_repository: repo='deb [arch=amd64,i386] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu {{ ansible_distribution_release }} main' state=present
    become: yes
    become_user: root

  - name: apt-get install
    apt: pkg={{ item }} update_cache=yes state=present
    with_items:
      - mariadb-server
      - mariadb-client
      - mariadb-common
      - libmariadbclient-dev
    become: yes
    become_user: root
