---
- hosts: localhost

  tasks:

  - name: Install production pre-requisites
    become: yes
    become_user: root
    apt: pkg={{ item }} state=present
    with_items:
      - nginx
      - supervisor
      - screen
      - vim
      - htop
      - git
