---
- hosts: localhost

  tasks:

  - name: Install production pre-requisites
    become: yes
    become_user: root
    apt: pkg={{ item }} state=present
    with_items:
      - nginx
      - supervisor
      - screen
      - vim
      - htop
      - git

  - name: Start supervisord with default configuration
    command: supervisord -c /etc/supervisor/supervisord.conf
    become: yes
    become_user: root
    when: ansible_distribution_version | version_compare('16.04', 'ge')
