---
  - name: Install production pre-requisites
    become: yes
    become_user: root
    apt: pkg={{ item }} state=present
    with_items:
      - nginx
      - supervisor
      - screen
      - vim
      - htop
      - git

  - name: Get-app erpnext app
    command: bench get-app erpnext https://github.com/frappe/erpnext.git --branch {{ branch }}
    args:
      chdir: '{{ bench_path }}'

  - name: Install erpnext app
    command: bench --site site1.local install-app erpnext # assumming we have created site1.local
    args:
      chdir: '{{ bench_path }}'

  - name: Setup production
    become: yes
    become_user: root
    command: bench setup production {{ ansible_user_id }}
    args:
      chdir: '{{ bench_path }}'

  - name: Setup Sudoers
    become: yes
    become_user: root
    command: bench setup sudoers {{ ansible_user_id }} # Assumption that we are using frappe user
    args:
      chdir: '{{ bench_path }}'
