"""Warn before commands that desync a managed bench from its control plane.

On Frappe Cloud the bench in the container is a *replica*, not the source of
truth -- Press owns the Bench and Site records and rebuilds the container from
an image on every deploy. A command run by hand inside the container can push
the two out of sync: an app installed here is missing from the dashboard, a
site dropped here is still billed, config written here is overwritten on the
next config push.

The guard is advisory. It asks before running, defaults to aborting, and gets
out of the way for anything non-interactive (the agent drives benches over
`docker exec` without a TTY) so automation is unaffected.
"""

# imports - standard imports
import os
import sys

# imports - third party imports
import click


# set by Press in the bench's common_site_config, which is bind-mounted into
# the container; also honoured as an env var so the marker can move into the
# image later without a bench release
MANAGED_CONFIG_KEY = "frappe_cloud"
MANAGED_ENV_VAR = "FRAPPE_CLOUD"
SKIP_ENV_VAR = "BENCH_SKIP_PROD_GUARD"

DOCS = "https://docs.frappe.io/cloud"

# command -> (what goes out of sync when it's run by hand, where the dashboard
# documents doing it properly). The doc link is None for the few commands the
# dashboard has no equivalent for. Aliases don't need an entry; _resolve_alias
# maps them onto whichever name is listed here.
GUARDED_COMMANDS = {
	# -- site state: tracked on the Site record --------------------------------
	"new-site": (
		"Frappe Cloud will not know about this site -- no billing, backups, DNS or "
		"TLS will be set up for it.",
		f"{DOCS}/sites/creating-a-new-site",
	),
	"drop-site": (
		"Frappe Cloud will still show this site as active while its database is "
		"gone.",
		f"{DOCS}/sites/drop-delete-your-site",
	),
	"install-app": (
		"Frappe Cloud tracks installed apps on the Site record. The app will be "
		"missing from the dashboard and will not survive the next deploy.",
		f"{DOCS}/installing-an-app",
	),
	"uninstall-app": (
		"Frappe Cloud tracks installed apps on the Site record. The dashboard will "
		"keep listing an app the site no longer has.",
		f"{DOCS}/how-to-uninstall-an-app-from-the-site",
	),
	"set-config": (
		"Frappe Cloud owns site_config.json and rewrites it on the next config "
		"push, discarding this change.",
		f"{DOCS}/sites/site-config",
	),
	"remove-config": (
		"Frappe Cloud owns site_config.json and rewrites it on the next config "
		"push, discarding this change.",
		f"{DOCS}/sites/site-config",
	),
	"reinstall": (
		"This drops and recreates the database. Frappe Cloud will not record it and "
		"its backup history will no longer match the site.",
		f"{DOCS}/sites/migrate-an-existing-site",
	),
	"rename": (
		"Frappe Cloud keys billing, DNS, TLS and backups on the site name. Renaming "
		"here orphans all of them.",
		f"{DOCS}/sites/custom-domains",
	),
	# -- bench state: tracked on the Bench record / Release Group ---------------
	"get-app": (
		"Apps come from the Release Group and are baked into the image. This app "
		"will disappear on the next deploy.",
		f"{DOCS}/benches",
	),
	"new-app": (
		"Apps come from the Release Group and are baked into the image. This app "
		"will disappear on the next deploy.",
		f"{DOCS}/benches",
	),
	"remove-app": (
		"Apps come from the Release Group and are baked into the image. The "
		"dashboard will keep listing an app this bench no longer has.",
		f"{DOCS}/benches",
	),
	"update": (
		"Frappe Cloud updates a bench by building and deploying a new image. "
		"Updating in place is discarded on the next deploy and desyncs the app "
		"hashes on record.",
		f"{DOCS}/benches/updating_a_bench",
	),
	"switch-to-branch": (
		"App branches come from the Release Group. Switching here desyncs the app "
		"hashes on record and is discarded on the next deploy.",
		f"{DOCS}/sites/version-upgrade",
	),
	"switch-to-develop": (
		"App branches come from the Release Group. Switching here desyncs the app "
		"hashes on record and is discarded on the next deploy.",
		f"{DOCS}/sites/version-upgrade",
	),
	"retry-upgrade": (
		"Frappe Cloud updates a bench by building and deploying a new image. "
		"Updating in place is discarded on the next deploy.",
		f"{DOCS}/benches/updating_a_bench",
	),
	"setup": (
		"Supervisor, nginx and the Python environment are generated by Frappe Cloud "
		"and its agent. Regenerating them here can leave the bench unable to start.",
		None,
	),
	"config": (
		"Frappe Cloud owns common_site_config.json and rewrites it on the next "
		"config push, discarding this change.",
		f"{DOCS}/benches/bench-config",
	),
	"start": (
		"Processes are supervised by Frappe Cloud. Starting them here fights the "
		"running containers for ports and sockets.",
		f"{DOCS}/benches/process-status",
	),
	"drop": (
		"This removes the bench directory that Frappe Cloud manages.",
		f"{DOCS}/dropping-a-bench-group",
	),
}


def is_managed_bench(bench_config=None) -> bool:
	"""Whether this bench's state is owned by Frappe Cloud."""
	if os.environ.get(MANAGED_ENV_VAR):
		return True

	if bench_config is None:
		from bench.config.common_site_config import get_config

		bench_config = get_config(".")

	return bool(bench_config.get(MANAGED_CONFIG_KEY))


def _resolve_alias(command: str):
	"""Return the name this table knows `command` by, if it's an alias.

	bench registers some commands under several names -- `get`/`get-app`,
	`remove`/`rm`/`remove-app` -- via MultiCommandGroup, which files one command
	object under each. An exact lookup would miss the aliases and wave through
	the very app changes the table is meant to catch, so resolve by identity
	rather than listing the aliases here and hoping the list stays current.
	"""
	from bench.commands import bench_command

	registered = bench_command.commands.get(command)
	if registered is None:
		return None

	for name, other in bench_command.commands.items():
		if other is registered and name in GUARDED_COMMANDS:
			return name

	return None


def get_guard(command: str):
	"""What goes out of sync if `command` is run on a managed bench, and its docs.

	Returns a `(reason, docs_url)` pair -- `docs_url` is None for the commands
	the dashboard has no equivalent for -- or None if the command is unguarded.
	"""
	if command in GUARDED_COMMANDS:
		return GUARDED_COMMANDS[command]

	canonical = _resolve_alias(command)
	return GUARDED_COMMANDS[canonical] if canonical else None


def confirm_if_managed(command: str, bench_config=None) -> None:
	"""Ask before running a command that desyncs a Frappe Cloud bench.

	Aborts with a non-zero exit code unless the user accepts. No-ops for
	unguarded commands, for benches Frappe Cloud does not manage, when
	BENCH_SKIP_PROD_GUARD is set, and when stdin is not a TTY -- the agent
	runs bench over `docker exec` without one.
	"""
	if not command or os.environ.get(SKIP_ENV_VAR):
		return

	# `bench update --help` shouldn't prompt for a command it never runs
	if {"--help", "-h"}.intersection(sys.argv):
		return

	guard = get_guard(command)
	if not guard:
		return

	if not is_managed_bench(bench_config):
		return

	if not sys.stdin.isatty():
		return

	reason, docs_url = guard
	invocation = " ".join(sys.argv[1:])

	click.secho("\nThis bench is managed by Frappe Cloud.", fg="yellow", bold=True)
	click.secho(f"\n  $ bench {invocation}\n", fg="yellow")
	click.echo(f"{reason}\n")
	click.echo("Use the Frappe Cloud dashboard instead.")
	if docs_url:
		click.secho(f"How to: {docs_url}", fg="cyan")
	click.echo()

	try:
		proceed = click.confirm("Run it anyway?", default=False)
	except click.Abort:
		proceed = False

	if not proceed:
		click.secho(
			f"Aborted. Set {SKIP_ENV_VAR}=1 to bypass this prompt.", fg="red", err=True
		)
		sys.exit(1)
