"""Warn before commands that desync a managed bench from its control plane.

On Frappe Cloud the bench in the container is a *replica*, not the source of
truth -- Press owns the Bench and Site records and rebuilds the container from
an image on every deploy. A command run by hand inside the container can push
the two out of sync: an app installed here is missing from the dashboard, a
site dropped here is still billed, config written here is overwritten on the
next config push.

The guard is advisory. It asks before running, defaults to aborting, and gets
out of the way for anything non-interactive (the agent drives benches over
`docker exec` without a TTY) so automation is unaffected.
"""

# imports - standard imports
import os
import sys

# imports - third party imports
import click


# set by Press in the bench's common_site_config, which is bind-mounted into
# the container; also honoured as an env var so the marker can move into the
# image later without a bench release
MANAGED_CONFIG_KEY = "frappe_cloud"
MANAGED_ENV_VAR = "FRAPPE_CLOUD"
SKIP_ENV_VAR = "BENCH_SKIP_PROD_GUARD"

# command -> what goes out of sync when it's run by hand
GUARDED_COMMANDS = {
	# -- site state: tracked on the Site record --------------------------------
	"new-site": (
		"Frappe Cloud will not know about this site -- no billing, backups, DNS or "
		"TLS will be set up for it."
	),
	"drop-site": (
		"Frappe Cloud will still show this site as active while its database is "
		"gone."
	),
	"install-app": (
		"Frappe Cloud tracks installed apps on the Site record. The app will be "
		"missing from the dashboard and will not survive the next deploy."
	),
	"uninstall-app": (
		"Frappe Cloud tracks installed apps on the Site record. The dashboard will "
		"keep listing an app the site no longer has."
	),
	"set-config": (
		"Frappe Cloud owns site_config.json and rewrites it on the next config "
		"push, discarding this change."
	),
	"remove-config": (
		"Frappe Cloud owns site_config.json and rewrites it on the next config "
		"push, discarding this change."
	),
	"restore": (
		"Frappe Cloud will not record the restore, and the site's data will no "
		"longer match the backups and app versions on record."
	),
	"reinstall": (
		"This drops and recreates the database. Frappe Cloud will not record it and "
		"its backup history will no longer match the site."
	),
	"migrate": (
		"Frappe Cloud runs migrations as part of a deploy. Migrating by hand can "
		"move the site past the app versions on record."
	),
	"rename": (
		"Frappe Cloud keys billing, DNS, TLS and backups on the site name. Renaming "
		"here orphans all of them."
	),
	"set-admin-password": (
		"Frappe Cloud stores the Administrator password. The credentials shown on "
		"the dashboard will stop working."
	),
	# -- bench state: tracked on the Bench record / Release Group ---------------
	"get-app": (
		"Apps come from the Release Group and are baked into the image. This app "
		"will disappear on the next deploy."
	),
	"new-app": (
		"Apps come from the Release Group and are baked into the image. This app "
		"will disappear on the next deploy."
	),
	"remove-app": (
		"Apps come from the Release Group and are baked into the image. The "
		"dashboard will keep listing an app this bench no longer has."
	),
	"update": (
		"Frappe Cloud updates a bench by building and deploying a new image. "
		"Updating in place is discarded on the next deploy and desyncs the app "
		"hashes on record."
	),
	"switch-to-branch": (
		"App branches come from the Release Group. Switching here desyncs the app "
		"hashes on record and is discarded on the next deploy."
	),
	"switch-to-develop": (
		"App branches come from the Release Group. Switching here desyncs the app "
		"hashes on record and is discarded on the next deploy."
	),
	"retry-upgrade": (
		"Frappe Cloud updates a bench by building and deploying a new image. "
		"Updating in place is discarded on the next deploy."
	),
	"pip": (
		"Python dependencies are installed at image build time. This change is lost "
		"on the next deploy and is invisible to Frappe Cloud."
	),
	"setup": (
		"Supervisor, nginx and the Python environment are generated by Frappe Cloud "
		"and its agent. Regenerating them here can leave the bench unable to start."
	),
	"config": (
		"Frappe Cloud owns common_site_config.json and rewrites it on the next "
		"config push, discarding this change."
	),
	"start": (
		"Processes are supervised by Frappe Cloud. Starting them here fights the "
		"running containers for ports and sockets."
	),
	"restart": (
		"Processes are supervised by Frappe Cloud, which restarts them through its "
		"agent."
	),
	"drop": "This removes the bench directory that Frappe Cloud manages.",
}


def is_managed_bench(bench_config=None) -> bool:
	"""Whether this bench's state is owned by Frappe Cloud."""
	if os.environ.get(MANAGED_ENV_VAR):
		return True

	if bench_config is None:
		from bench.config.common_site_config import get_config

		bench_config = get_config(".")

	return bool(bench_config.get(MANAGED_CONFIG_KEY))


def get_guard_reason(command: str):
	"""Return what goes out of sync if `command` is run on a managed bench."""
	return GUARDED_COMMANDS.get(command)


def confirm_if_managed(command: str, bench_config=None) -> None:
	"""Ask before running a command that desyncs a Frappe Cloud bench.

	Aborts with a non-zero exit code unless the user accepts. No-ops for
	unguarded commands, for benches Frappe Cloud does not manage, when
	BENCH_SKIP_PROD_GUARD is set, and when stdin is not a TTY -- the agent
	runs bench over `docker exec` without one.
	"""
	if not command or os.environ.get(SKIP_ENV_VAR):
		return

	# `bench update --help` shouldn't prompt for a command it never runs
	if {"--help", "-h"}.intersection(sys.argv):
		return

	reason = get_guard_reason(command)
	if not reason:
		return

	if not is_managed_bench(bench_config):
		return

	if not sys.stdin.isatty():
		return

	invocation = " ".join(sys.argv[1:])

	click.secho("\nThis bench is managed by Frappe Cloud.", fg="yellow", bold=True)
	click.secho(f"\n  $ bench {invocation}\n", fg="yellow")
	click.echo(f"{reason}\n")
	click.echo("Use the Frappe Cloud dashboard instead.\n")

	try:
		proceed = click.confirm("Run it anyway?", default=False)
	except click.Abort:
		proceed = False

	if not proceed:
		click.secho(
			f"Aborted. Set {SKIP_ENV_VAR}=1 to bypass this prompt.", fg="red", err=True
		)
		sys.exit(1)
