version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            sudo pip install --ignore-installed setuptools
            sudo pip install urllib3 pyOpenSSL ndg-httpsclient pyasn1
            sudo cp -r ~/.ssh/* /root/.ssh
            mkdir -p ~/.bench
            mkdir -p /tmp/.bench
            cp -r ~/repo/* ~/.bench
            cp -r ~/repo/* /tmp/.bench

      - run:
          name: Install Bench (Production)
          command: sudo python ~/repo/playbooks/install.py --user travis --run-travis --production

      - run:
          name: Setup Tests
          command: |
            cd ~
            sudo pip install --upgrade pip==19.3.1
            sudo pip install -e ~/.bench

      - run:
          name: Run Tests
          command: sudo -E python -m unittest -v bench.tests.test_setup_production
