---
- include: centos.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 6

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Add configuration
  template: src={{ mysql_conf_tpl }} dest={{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }} owner=root group=root mode=0644
  when: mysql_conf_tpl != 'change_me' and ansible_distribution != 'Debian'
  notify: restart mysql

- include: debian.yml
  when: ansible_distribution == 'Debian'

- name: Add configuration
  template: src=files/debian_mariadb_config.cnf dest={{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }} owner=root group=root mode=0644
  when: mysql_conf_tpl != 'change_me' and ansible_distribution == 'Debian'
  notify: restart mysql

- name: Start and enable service
  service: name=mysql state=started enabled=yes

- debug:
    msg: "{{ mysql_root_password }}"

- include: mysql_secure_installation.yml
  when: mysql_root_password is defined

- debug: var=mysql_secure_installation
  when: mysql_secure_installation and mysql_root_password is defined
