---
  - hosts: localhost

  # Install the common pre-requisites for the setting up bench
  - include: install.yml

  - include: includes/setup_production_ubuntu.yml
    when: ansible_distribution == 'Ubuntu'

  # - include: includes/setup_production_centos.yml
  #   when: ansible_distribution == 'CentOS'

  # Setup Bench for production environment
  - include: includes/setup_bench_production.yml

  # Setup SELinux Policy
  - include: includes/setup_selinux_policy.yml
