---
- hosts: localhost
  tasks:
  - name: insert/update inputrc for history
    blockinfile:
      dest: "/home/{{ ansible_user_id }}/.inputrc"
      create: yes
      block: |
        ## arrow up
        "\e[A":history-search-backward
        ## arrow down
        "\e[B":history-search-forward